import type { Metadata } from 'next';
import './globals.css';
import { Outfit } from 'next/font/google';
import { SparklesCore } from '@/components/ui/sparkles';

const outfit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-[#11071F] ${outfit.className} h-screen`}>
        {children}
      </body>
    </html>
  );
}
